### ISSUE TITLE
Allow ACCESS_TOKEN from ENV

### ISSUE THREAD

**Issue by ekeih** [ekeih/OmNomNom#20]
It would be nice to allow to set the ACCESS_TOKEN as environment variable. This is useful to deploy  OmNomNom in a docker container.

```
if env
  use env
else if
  use config.py
else
  throw error
fi
```

**Comment by MetalMatze** [comment]
Ping me if this is integrated, then I will add a flag to the `Dockerfile` if you want me to.

**Comment by ekeih** [comment]
The token has to be defined by an environment variable TELEGRAM_BOT_AUTH_TOKEN since f369ece4cf44540618c8d345e643a5cd049c5cd3.
The configuration file is not longer supported.
