### ISSUE TITLE
Add Cafe Nero at TU Bibliothek

### ISSUE THREAD

**Issue by numbleroot** [ekeih/OmNomNom#22]
I don't know whether you are already parsing some PDF menus anywhere, but if so, it would be nice if you could add the Cafe Nero located at TU Universitätsbibliothek as well.

The link to the current day's menu is embedded into an `iframe` view of the PDF uploaded to Dropbox... Maybe you can work some magic here and extract the meals anyways.
Link to menu: [http://cafenero.net/speisekarte/](http://cafenero.net/speisekarte/)

Thanks for the awesome bot! :)

**Comment by ekeih** [comment]
The meals of Cafe Nero are now available by `/tu_cafenero`.

**Comment by numbleroot** [comment]
Thanks a lot! 11/10!
