### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ekeih** [ekeih/OmNomNom#27]
Currently the bot is missing mostly everything you would expect from a well documented project.

If you are thinking about contributing code or just want to run the bot yourself, please let me know, so I can prioritize this issue ;-)

**Comment by DopeforHope** [comment]
Could you provide a basic developer example how to start the bot locally and maybe how to test it?
This would allow interested developers and especially students to contribute to the project.
Even if it's a one-liner, having a starting point as a newbie would be great.

Thank you in advance

**Comment by ekeih** [comment]
Hi,

to get startet you can take the following steps:

1. Create a bot token by talking to https://t.me/botfather
2. Talk to you dev-bot by sending `/start` to it.
3. `git clone git@github.com:ekeih/OmNomNom.git && cd OmNomNom`
4. Create virtual python environment: `mkvirtualenv -p $(which python3) omnomnom`
5. Install dependencies: `pip install -r requirements.txt -r requirements-dev.txt`
6. Install the git package: `pip install -e .`
7. Install a local redis server and start it with an empty database.
8. `export OMNOMNOM_AUTH_TOKEN=your_bot_token`
9. `export OMNOMNOM_ADMIN=your_own_telegram_id`
10. `omnbot-frontend` to start the frontend that communicates with the telegram API.
11. `omnbot-worker` to start a worker that parses websites.
12. `omnbot-beat` to schedule regular cache updates.
13. `omnbot-housekeeping` to handle some maintenance tasks like sending error messages to you.

I will try to include this with more details in the documentation. Let me know if you have any questions or if I missed something.

Best regards
Max

**Comment by ekeih** [comment]
@DopeforHope Feel free to talk to me via https://t.me/ekeih if you have any questions.

**Comment by ekeih** [comment]
@DopeforHope Additional documentation is available at https://docs.omnbot.io/ but currently it is only generated from the docstrings.

I attached an overview of the architecture. The picture is explained in: https://fotoallerlei.com/34c3-i-talked-about-omnomnom/

![bla](https://user-images.githubusercontent.com/3430656/35783698-b6651caa-0a0b-11e8-9124-3c628d3b22ca.png)
