### ISSUE TITLE
Continuous Delivery

### ISSUE THREAD

**Issue by ekeih** [ekeih/OmNomNom#30]
Currently a push to master only triggers a build at hub.docker.com but it needs manual interaction to get deployed. This could and should be automated.

**Comment by ekeih** [comment]
Push to dev-Branch -> Build at hub.docker.com -> Deployment of dev-Bot ✔️

**Comment by metalmatze** [comment]
I have this setup and running with drone.io self-hosted. Let me know if you need help.

**Comment by ekeih** [comment]
Hi @metalmatze,

thank you for your offer! Currently I use https://github.com/adnanh/webhook to trigger new deployments. It works great for the dev- and production-bots. For now it runs smoothly but in case I switch to drone.io in the future I will keep your offer in mind.

Thanks you and best regards
Max
