### ISSUE TITLE
Support for Studentenwerk Kassel

### ISSUE THREAD

**Issue by markusressel** [ekeih/OmNomNom#41]
Another canteen @ Uni Kassel (the main one)

https://www.studentenwerk-kassel.de/meta/speiseplan/zentralmensa-arnold-bode-strasse/

**Comment by ekeih** [comment]
I will try to support all Studentenwerk Kassel canteens in one parser.

**Comment by ekeih** [comment]
Wow, the use different websites / layouts for different canteens... 🙄

**Comment by ekeih** [comment]
Okay, I will close this for now.

If someone finds this issue and wants to implement it, I am happy to open it again!
