### ISSUE TITLE
Personalkantine - wrong date on website -> no information for today

### ISSUE THREAD

**Issue by DopeforHope** [ekeih/OmNomNom#44]
Hi,

today the date at the Personalkantine website is wrong: "026.02.2018"
A copy of todays website can be found in the attachments.
I had quick look at the code and have no idea how to fix this. But maybe someone else has one.
Additionally this maybe leads to an overlap when the menu for the 26.02.2018 is reed.
But I would assume that this will just be overwritten.

Website:
[website.zip](https://github.com/ekeih/OmNomNom/files/1689813/website.zip)

**Comment by ekeih** [comment]
Hi,

thank you for bringing this to my attention and for attaching the website dump!

To correct such an (manual) error it would be necessary to make a decision between the following options:

- 026.02.2018 ->  26.02.2018
- 026.02.2018 ->  02.02.2018
- 026.02.2018 ->  06.02.2018
- 026.02.2018 ->  2.02.2018
- 026.02.2018 ->  6.02.2018

With enough effort it would be possible to guess the correct date as we are aware of the current date and know the other dates from the website. However it would add significant complexity to the parser to catch one rare user-caused error.
Additionally they could add any kind of numbers or characters by mistake which causes an error in the parser and it would be impossible to catch them all.

If they start to include more errors I am willing to build a more complex and more clever parser. But currently I will close this issue as "won't fix".

Let me know if you have any other thoughts about this issue.

Thank you again for reporting this issue and please feel free to report more problems if they occur.

Best regards
Max
