### ISSUE TITLE
Remove "Tip" message from response

### ISSUE THREAD

**Issue by markusressel** [ekeih/OmNomNom#49]
F.ex. /march prints a tip message at the bottom:

```
Tipp: Wenn Sie dieses Fenster schließen, wird es nur erneut durch Leeren des Cache wieder angezeigt.
```

which has nothing to do with the list of meals. This text should be removed from the bot response.

**Comment by ekeih** [comment]
Thanks for bringing this to my attention :slightly_smiling_face: 
Fixed in 192c914cc6955d0a0268526bfd6cd1776b80a274
