### ISSUE TITLE
Show menu in English or other languages

### ISSUE THREAD

**Issue by haseeb1431** [ekeih/OmNomNom#63]
Can we translate the menu in English any other language as well.  I will be happy to work with you on this feature if you needed. Thanks

**Comment by ekeih** [comment]
Hi @haseeb1431,

the menus are parsed from German websites, so this would require some automated translation. I see two challenges:

1. Automated translation of the menus.

2. The users need a way to specify the language. I think something like `/tu_mensa tomorrow en` is to complicated as a user interface. Maybe we need to store user preferences on the server. (This would also enable the bot to send the different prices for students, employees and guests.)

Do you have some ideas how to solve those?

Personally I am not sure if it is worth the time for development and maintenance but I am open for arguments to convince me. Either way I will not be able to invest time into this before September.

**Comment by haseeb1431** [comment]
1. We can use some third party API e.g. [Azure translation service](https://azure.microsoft.com/en-us/services/cognitive-services/translator-text-api/) or google API with this community project
2. I think we can store it as the settings while not changing the existing interface

We can mark this something as good to have.

One quick solution we can do is give a button or something which just opens google translate and copies all the menu there and then user can take it further.
